tst_rast: tst_rast.o raster.o rast_asm.o fonts.o
	cc68x -g tst_rast.o raster.o fonts.o rast_asm.o -o tst_rast

tst_rast.o: tst_rast.c raster.h fonts.h
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

fonts.o: fonts.c raster.h
	cc68x -g -c fonts.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

clean:
	rm rast_asm.o
