tst_rast: tst_rast.o raster.o rast_asm.o fonts.o splash.o sprites.o model.o
	cc68x -g tst_rast.o raster.o fonts.o splash.o sprites.o rast_asm.o model.o -o tst_rast

tst_model: tst_model.o raster.o rast_asm.o fonts.o splash.o sprites.o model.o plyrsm.o
	cc68x -g tst_model.o raster.o fonts.o splash.o sprites.o rast_asm.o model.o plyrsm.o -o tst_model

tst_rast.o: tst_rast.c raster.h fonts.h
	cc68x -g -c tst_rast.c

tst_model.o: tst_model.c raster.h fonts.h model.h
	cc68x -g -c tst_model.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

model.o: model.c raster.h
	cc68x -g -c model.c

fonts.o: fonts.c raster.h
	cc68x -g -c fonts.c

splash.o: splash.c raster.h
	cc68x -g -c splash.c

sprites.o: sprites.c raster.h
	cc68x -g -c sprites.c

plyrsm.o: plyrsm.c
	gen -D -L2 plyrsm.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

clean:
	rm rast_asm.o
