tst_rast: bin/tst_rast.o bin/raster.o bin/rast_asm.o bin/fonts.o bin/splash.o bin/sprites.o bin/model.o bin/plyrsm.o bin/events.o bin/render.o bin/anims.o
	cc68x -g bin/tst_rast.o bin/raster.o bin/rast_asm.o bin/fonts.o bin/splash.o bin/sprites.o bin/model.o bin/plyrsm.o bin/events.o bin/render.o bin/anims.o -o tst_rast

tst_model: bin/tst_model.o bin/raster.o bin/rast_asm.o bin/fonts.o bin/splash.o bin/sprites.o bin/model.o bin/plyrsm.o bin/events.o bin/render.o bin/anims.o
	cc68x -g bin/tst_model.o bin/raster.o bin/rast_asm.o bin/fonts.o bin/splash.o bin/sprites.o bin/model.o bin/plyrsm.o bin/events.o bin/render.o bin/anims.o -o tst_model

tst_render: bin/tst_render.o bin/raster.o bin/rast_asm.o bin/fonts.o bin/splash.o bin/sprites.o bin/model.o bin/plyrsm.o bin/events.o bin/render.o bin/anims.o
	cc68x -g bin/tst_render.o bin/raster.o bin/rast_asm.o bin/fonts.o bin/splash.o bin/sprites.o bin/model.o bin/plyrsm.o bin/events.o bin/render.o bin/anims.o -o tst_render

tst_game: bin/tst_game.o bin/raster.o bin/rast_asm.o bin/fonts.o bin/splash.o bin/sprites.o bin/model.o bin/plyrsm.o bin/events.o bin/render.o bin/anims.o bin/game.o
	cc68x -g bin/tst_game.o bin/raster.o bin/rast_asm.o bin/fonts.o bin/splash.o bin/sprites.o bin/model.o bin/plyrsm.o bin/events.o bin/render.o bin/anims.o bin/game.o -o tst_game

bin/tst_rast.o: tst_rast.c raster.h fonts.h
	cc68x -g -c tst_rast.c -o bin/tst_rast.o

bin/tst_model.o: tst_model.c raster.h fonts.h model.h events.h plyrsm.h types.h
	cc68x -g -c tst_model.c -o bin/tst_model.o

bin/tst_render.o: tst_render.c anims.h events.h fonts.h game.h model.h plyrsm.h raster.h render.h types.h splash.h sprites.h
	cc68x -g -c tst_render.c -o bin/tst_render.o

bin/tst_game.o: tst_game.c anims.h events.h fonts.h game.h model.h plyrsm.h raster.h render.h types.h splash.h sprites.h
	cc68x -g -c tst_game.c -o bin/tst_game.o

bin/anims.o: anims.c anims.h
	cc68x -g -c anims.c -o bin/anims.o

bin/events.o: events.c events.h 
	cc68x -g -c events.c -o bin/events.o

bin/fonts.o: fonts.c fonts.h
	cc68x -g -c fonts.c -o bin/fonts.o

bin/game.o: game.c game.h raster.h
	cc68x -g -c game.c -o bin/game.o

bin/model.o: model.c model.h
	cc68x -g -c model.c -o bin/model.o

bin/plyrsm.o: plyrsm.c plyrsm.h	
	cc68x -g -c plyrsm.c -o bin/plyrsm.o

bin/raster.o: raster.c raster.h
	cc68x -g -c raster.c -o bin/raster.o

bin/render.o: render.c render.h
	cc68x -g -c render.c -o bin/render.o

bin/splash.o: splash.c splash.h
	cc68x -g -c splash.c -o bin/splash.o

bin/sprites.o: sprites.c sprites.h
	cc68x -g -c sprites.c -o bin/sprites.o

bin/rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s -obin/rast_asm.o

clean:
	rm tst_game
