#ifndef SPRITES_H
#define SPRITES_H

#include "types.h"

extern const UINT16 bm_avatarIdleF1_RS [];
extern const UINT16 bm_avatarIdleF3_RS [];
extern const UINT16 bm_avatarIdleF2_RS [];

extern const UINT16 bm_avatarIdleF1_LS [];
extern const UINT16 bm_avatarIdleF2_LS [];
extern const UINT16 bm_avatarIdleF3_LS [];

extern const UINT16 bm_avatarRunF1_RS [];
extern const UINT16 bm_avatarRunF2_RS [];
extern const UINT16 bm_avatarRunF3_RS [];

extern const UINT16 bm_avatarRunF1_LS [];
extern const UINT16 bm_avatarRunF2_LS [];
extern const UINT16 bm_avatarRunF3_LS [];

#endif
